services:
  db:
    image: postgres:15
    container_name: irc_db
    restart: always
    environment:
      POSTGRES_DB: ircdb
      POSTGRES_USER: ircuser
      POSTGRES_PASSWORD: ircpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    container_name: irc_server
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: irc_client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres-data:
